### ISSUE TITLE
全局设置了只能竖屏的情况下，横屏没法使用

### ISSUE THREAD

**Issue by Ohuisang** [easefun/polyv-ios-client-demo#10]
![853e4d70-6bba-476f-b5ad-c327bcdd8d6c](https://cloud.githubusercontent.com/assets/4980617/15202435/e81062d2-182c-11e6-9972-fac950a029dd.png)

**Comment by bqlin** [comment]
是会这样的 所以要把横屏也勾选

**Comment by Ohuisang** [comment]
酱紫。因为肯定有些项目是没有全部页面适配自适应的。所有一般都没勾选横屏。

**Comment by bqlin** [comment]
我试试能不能实现

**Comment by bqlin** [comment]
还是希望你把横屏都勾选，否则你只能使用 window 模式的播放器。

**Comment by Ohuisang** [comment]
恩 哈哈 自己也找了找旋转的试了下基本可以，但是项目里集成了友盟的社区不好修改群不文件，，。没法全局控制旋转。。只能用window 模式的了

**Comment by bqlin** [comment]
我明天出一个控制全局旋转的 wiki，详细说说这个问题的解决。
