### ISSUE TITLE
全屏模式

### ISSUE THREAD

**Issue by wanglang** [easefun/polyv-ios-client-demo#12]
在showinwindow的情况下，全屏模式只是播放器全屏了，实际上状态栏还是原来的位置，而且一来通知，就会自动退出全屏模式，这个是否可以优化一下呢？

**Comment by bqlin** [comment]
窗口模式下，为了不影响底部控制器的旋转方向，使用旋转变形方式全屏的，现在在全屏时把状态栏隐藏了。
