### ISSUE TITLE
必须要支持ATS了

### ISSUE THREAD

**Issue by emilyZhouwm** [easefun/polyv-ios-client-demo#16]
2017年1月1日 App Store中的所有应用都必须启用 App Transport Security安全功能，否则极有可能被拒

你家的NSAppTransportSecurity该怎么写？

**Comment by Zeaa** [comment]
可将HTTP的网络访问改为HTTPS或在info.plist中将使用HTTP的链接设置为白名单的方式（NSExceptionDomains键），目前正全面升级HTTPS中，将采用更安全的网络访问方式

**Comment by bqlin** [comment]
现在所有 API 接口已使用 HTTPS 连接。
