### ISSUE TITLE
联系保利威视销售完成 ATS 升级？

### ISSUE THREAD

**Issue by Ohuisang** [easefun/polyv-ios-client-demo#17]
sdk已更新，并配置好。但是还是不能播放。

问题出在 联系保利威视销售完成 ATS 升级？怎么联系和说明？

**Comment by bqlin** [comment]
http://www.polyv.net/company/#contact

现在试试能不能播放。

**Comment by bqlin** [comment]
现在最新版本直接更新SDK即可完成升级。
