### ISSUE TITLE
PvUrlSessionDownload内存泄露？

### ISSUE THREAD

**Issue by frankfan1990** [easefun/polyv-ios-client-demo#20]
使用PvUrlSessionDownload下载视频,其中设置代理 [downloader setDownloadDelegate:self]后，点击页面的返回按钮,UIViewController没有被销毁（self是该UIViewController的实例

**Comment by R0uter** [comment]
我的解决办法是单独一个单件作为下载管理器，这个单件用作`PvUrlSessionDownload`的`delegate`。
