### ISSUE TITLE
播放视频时，crash

### ISSUE THREAD

**Issue by sunlei4076** [easefun/polyv-ios-client-demo#21]
提示如下
NSInvalidArgumentException
An AVPlayerItem cannot be associated with more than one instance of AVPlayer
CoreFoundation ___exceptionPreprocess

**Comment by sunlei4076** [comment]
http://stackoverflow.com/questions/12041260/an-avplayeritem-cannot-be-associated-with-more-than-one-instance-of-avplayer
能使用这个方法解决吗

**Comment by bqlin** [comment]
出现这个问题是因为我们使用的播放器是继承于`MPMoviePlayerController `，因此是不能同时存在两个播放器对象的。

**Comment by sunlei4076** [comment]
是因为我这边没有销毁便又初始化另一个播放器的原因吗

**Comment by bqlin** [comment]
可能是。
