### ISSUE TITLE
下载时，[PvUrlSessionDownload startTask]，数组越界

### ISSUE THREAD

**Issue by sunlei4076** [easefun/polyv-ios-client-demo#22]
*** -[__NSArrayI objectAtIndex:]: index 18446744073709551615 beyond bounds [0 .. 2]
ZejiwangxiaoiOS -[PvUrlSessionDownload startTask] (PvUrlSessionDownload.m:)

**Comment by sunlei4076** [comment]
是因为index没有初始化的原因吗？
同时可以加一个index是否在数组的范围的判断

**Comment by bqlin** [comment]
还有其他调试信息吗 我不能确定你崩溃到哪个位置

**Comment by sunlei4076** [comment]
已截图反馈

**Comment by sunlei4076** [comment]
<img width="1252" alt="2017-04-11 10 53 08" src="https://cloud.githubusercontent.com/assets/13211268/24890908/18d92686-1ea5-11e7-9f0d-3b3855426917.png">

**Comment by sunlei4076** [comment]
<img width="607" alt="2017-04-11 11 01 51" src="https://cloud.githubusercontent.com/assets/13211268/24891134/6914efee-1ea6-11e7-9e59-41232389f439.png">
