### ISSUE TITLE
截图并保存到相册时，如果是本地视频会失败

### ISSUE THREAD

**Issue by sunlei4076** [easefun/polyv-ios-client-demo#23]
![2017-03-16 10 43 06](https://cloud.githubusercontent.com/assets/13211268/23979587/68fb2fbc-0a35-11e7-869c-f5c7a20d788f.png)
可以看到sign里的vid获取为null

**Comment by sunlei4076** [comment]
在这种情况下（播放本地视频）
也无法获得视频的清晰度列表

**Comment by bqlin** [comment]
提出的问题已经修复了。另外本地视频是只允许有一个清晰度的，因此没有清晰度列表。
