### ISSUE TITLE
下载视频时，经常出现下载快结束时。不再回调

### ISSUE THREAD

**Issue by sunlei4076** [easefun/polyv-ios-client-demo#24]
func dataDownloadAtPercent(downloader: PvUrlSessionDownload!, withVid vid: String!, percent aPercent: NSNumber!) {
        print("dataDownloadAtPercent",vid,aPercent）
    }

这个下载百分比回调函数，
在下载到95%-98%左右，会停止回调，导致下载进度也停止，
但是再次开始任务时，这个下载回调才开始，会很快到进度100%

**Comment by sunlei4076** [comment]
[IMG_0594.zip](https://github.com/easefun/polyv-ios-client-demo/files/866916/IMG_0594.zip)

这个是录的视频，可以参考（8MB）

**Comment by sunlei4076** [comment]
今天又录了个视频（18.9MB），只有重新开始时才能结束
[IMG_0599.zip](https://github.com/easefun/polyv-ios-client-demo/files/869574/IMG_0599.zip)

**Comment by sunlei4076** [comment]
1.2.2开始到最新的commit都有这个问题

**Comment by bqlin** [comment]
试试 dev 分支下最新的版本时候能解决你问题。

**Comment by sunlei4076** [comment]
我测试了 ，下载已经没问题了
但是非下载视频无法播放，demo里的也是

**Comment by sunlei4076** [comment]
![Uploading Simulator Screen Shot 2017年3月27日 19.10.51.png…]()

**Comment by sunlei4076** [comment]
![simulator screen shot 2017 3 27 19 10 51](https://cloud.githubusercontent.com/assets/13211268/24353709/6e23c2de-1321-11e7-9484-ce763ca368ec.png)

**Comment by bqlin** [comment]
iOS 什么版本？机型？

**Comment by sunlei4076** [comment]
昨天测试有问题  模拟器和真机都是
现在已经可以播放了
