### ISSUE TITLE
MPMovieView 没有释放

### ISSUE THREAD

**Issue by Ohuisang** [easefun/polyv-ios-client-demo#3]
使用MLeakFinder：

```
View-ViewController stack: (
    DetailViewController2,
    UIView,
    MPMovieView
)'    
```

**Comment by bqlin** [comment]
MLeakFinder 是哪个工具？

**Comment by Ohuisang** [comment]
你可以试下 https://github.com/Zepo/MLeaksFinder
你的 demo设置下  ![9c2dd387-b3e3-4ede-b421-073eb0600e09 png](https://cloud.githubusercontent.com/assets/4980617/13941368/f4584e5c-f021-11e5-86a7-34584b5b6108.jpeg)

**Comment by bqlin** [comment]
我试试

**Comment by Zeaa** [comment]
@linsyorozuya 您再试下
