### ISSUE TITLE
播放视频崩溃

### ISSUE THREAD

**Issue by sunlei4076** [easefun/polyv-ios-client-demo#33]
<img width="708" alt="2017-05-26 14 55 59" src="https://cloud.githubusercontent.com/assets/13211268/26484221/7fba5af4-4223-11e7-97b0-d012cfc571dd.png">

**Comment by sunlei4076** [comment]
版本是1.3.0

**Comment by sunlei4076** [comment]
具体情况是，播放已下载视频，缓冲进度条懂了几次后偶尔会停止，当播放进度到达缓冲进度条后，就会发生


播放在线视频也会发生

**Comment by sunlei4076** [comment]
现在是一个很严重的问题，希望解决

**Comment by sunlei4076** [comment]
<img width="1012" alt="2017-06-19 10 35 29" src="https://user-images.githubusercontent.com/13211268/27267490-64106314-54db-11e7-91b8-fac7a6e6e153.png">

第18行的log信息

**Comment by sunlei4076** [comment]
@bqlin

**Comment by bqlin** [comment]
非加密视频？

**Comment by bqlin** [comment]
你说的问题后面的版本有修复了，你用最新的SDK试试
