### ISSUE TITLE
PolySDK  初始化播放器时  setVid崩溃

### ISSUE THREAD

**Issue by ConnyYue** [easefun/polyv-ios-client-demo#34]
if (!_videoPlayer) {
            [_webView layoutIfNeeded];
            _videoPlayer = [[SkinVideoViewController alloc] initWithFrame:_webView.bounds];
            [_webView addSubview:_videoPlayer.view];
            [_videoPlayer setParentViewController:self];
            [_videoPlayer keepNavigationBar:YES];
            [_videoPlayer setHeadTitle:_replay.name];
            [_videoPlayer setNavigationController:self.navigationController];
            [_videoPlayer setMovieSourceType:MPMovieSourceTypeStreaming];
            [_videoPlayer enableDanmu:YES];
            [_videoPlayer setEnableDanmuDisplay:NO];    // 不显示弹幕按钮
        }
        _videoPlayer.contentURL = nil;
        [_videoPlayer setVid:_replay.polyv_id];

        // 注册监听
        [_videoPlayer configObserver];
        __weak typeof(self) weakself = self;
        [_videoPlayer setFullscreenBlock:^{
            weakself.titleLbl.hidden = TRUE;
            weakself.titleImgView.hidden = TRUE;
        }];
        [_videoPlayer setShrinkscreenBlock:^{
            weakself.titleLbl.hidden = FALSE;
            weakself.titleImgView.hidden = FALSE;
        }];

![1](https://user-images.githubusercontent.com/16607263/26915900-917b356a-4c5a-11e7-8d5c-15cb8f5cc0a7.png)

**Comment by bqlin** [comment]
这个问题看起来像是userid或sdk加密串没配置好
