### ISSUE TITLE
[PLVM3u8DownloaderWithDownloadTask stopDownload ] crash

### ISSUE THREAD

**Issue by sunlei4076** [easefun/polyv-ios-client-demo#37]
![wechatimg23](https://user-images.githubusercontent.com/13211268/27267242-a1480d1a-54d9-11e7-9212-d6427f7d437c.jpeg)

**Comment by bqlin** [comment]
已跟进

**Comment by sunlei4076** [comment]
类似的地方 crash 
<img width="1305" alt="2017-06-19 17 25 20" src="https://user-images.githubusercontent.com/13211268/27278558-4d6ce4b4-5514-11e7-8f28-b27ae5242df6.png">

**Comment by sunlei4076** [comment]
@bqlin

**Comment by sunlei4076** [comment]
<img width="1342" alt="2017-06-19 17 30 35" src="https://user-images.githubusercontent.com/13211268/27278799-0bc1db7c-5515-11e7-8adc-4a74b8b24af7.png">

**Comment by bqlin** [comment]
用昨天更新的还有问题？

**Comment by sunlei4076** [comment]
自己测试时未发现
线上监测数据发现的
还未使用更新版本

**Comment by sunlei4076** [comment]
依然有问题。
@bqlin

**Comment by sunlei4076** [comment]
<img width="600" alt="2017-06-23 09 49 38" src="https://user-images.githubusercontent.com/13211268/27463319-7fda7640-57f9-11e7-8465-f72e82d5520e.png">
<img width="611" alt="2017-06-23 09 49 50" src="https://user-images.githubusercontent.com/13211268/27463333-869cb006-57f9-11e7-8deb-2063714ca21b.png">
<img width="602" alt="2017-06-23 09 50 06" src="https://user-images.githubusercontent.com/13211268/27463335-88a3cda8-57f9-11e7-94d4-4a6dfe4dbc58.png">
<img width="608" alt="2017-06-23 09 50 23" src="https://user-images.githubusercontent.com/13211268/27463337-8b2f272a-57f9-11e7-9388-18ec2c6848e8.png">
<img width="596" alt="2017-06-23 09 52 38" src="https://user-images.githubusercontent.com/13211268/27463374-bc450a28-57f9-11e7-9b52-9b311334ed07.png">

**Comment by sunlei4076** [comment]
still 


<img width="958" alt="5b171dc0-9113-497b-b19c-0f718e93c95c" src="https://user-images.githubusercontent.com/13211268/27567119-41dcb332-5b1c-11e7-9272-57be274dad58.png">



<img width="913" alt="2e04893f-2b54-418e-9413-0c89faab05d9" src="https://user-images.githubusercontent.com/13211268/27567121-455804d0-5b1c-11e7-8feb-2c2ec8560196.png">

**Comment by sunlei4076** [comment]
<img width="587" alt="d8d91d56-ef60-4578-9515-8a9dad7d5812" src="https://user-images.githubusercontent.com/13211268/27846311-c5257bc8-6168-11e7-9eb4-09a679890b75.png">

依然存在
@bqlin

**Comment by sunlei4076** [comment]
![jietu20170714-145623](https://user-images.githubusercontent.com/13211268/28201682-b91a7048-68a4-11e7-857a-1ce47cfc75f3.jpg)



类似的crash
@bqlin

**Comment by sunlei4076** [comment]
<img width="970" alt="qq20170718-153818 2x" src="https://user-images.githubusercontent.com/13211268/28305749-6aaa7b5a-6bcf-11e7-8203-5a8b1030eb65.png">

v1.4.0
still
@bqlin

**Comment by bqlin** [comment]
1.4.0 版本只修复了播放器引起的崩溃问题，下载器引起的崩溃问题还在修。
