### ISSUE TITLE
An AVPlayerItem cannot be associated with more than one instance of AVPlayer CoreFoundation ___exceptionPreprocess

### ISSUE THREAD

**Issue by sunlei4076** [easefun/polyv-ios-client-demo#38]
issues已经有了类似的问题，已经成为首位崩溃的问题
<img width="793" alt="741a3fe9-c2e6-4984-a8f1-51b0edbf1fd6" src="https://user-images.githubusercontent.com/13211268/27527903-6dfae62e-5a80-11e7-95f4-cc26aeba8652.png">

**Comment by sunlei4076** [comment]
@bqlin

**Comment by sunlei4076** [comment]
貌似这样可以
[http://blog.k-res.net/archives/1193.html](http://blog.k-res.net/archives/1193.html)

**Comment by bqlin** [comment]
可以试试最新的release版本，[polyv-ios-client-demo release v1.4.0](https://github.com/easefun/polyv-ios-client-demo/releases/tag/v1.4.0)，对应的是 dev 分支的最新代码。该版本使用 AVPlayer 改写了原来使用的播放器，看能不能解决你的问题。
