### ISSUE TITLE
An instance 0x174037ea0 of class AVKeyPathFlattener was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x174035240> ( <NSKeyValueObservance 0x1702547f0: Observer: 0x17407b200, Key path: operationCount, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x1742545e0> )

### ISSUE THREAD

**Issue by sunlei4076** [easefun/polyv-ios-client-demo#39]
偶尔出现：

<img width="791" alt="18d7a6ca-3b9e-47f6-a53f-b26e24469bcc" src="https://user-images.githubusercontent.com/13211268/27528070-3644389c-5a81-11e7-8c04-bd19fee824df.png">
<img width="792" alt="7f311bc5-908b-4ac8-b4cd-2a2a9312d059" src="https://user-images.githubusercontent.com/13211268/27528085-50186e1e-5a81-11e7-8c16-61742d22efa7.png">
@bqlin

**Comment by KxShare** [comment]
楼主解决了吗

**Comment by sunlei4076** [comment]
@KxShare 没解决
![jietu20170712-144608](https://user-images.githubusercontent.com/13211268/28105205-12842b00-6711-11e7-9abe-1e8fd95eb705.jpg)

目前崩溃列表，这个占大头，一眼望去全是它

**Comment by bqlin** [comment]
可以试试最新的release版本，[polyv-ios-client-demo release v1.4.0](https://github.com/easefun/polyv-ios-client-demo/releases/tag/v1.4.0)，对应的是 dev 分支的最新代码。该版本使用 AVPlayer 改写了原来使用的播放器，看能不能解决你的问题。
