### ISSUE TITLE
1.4.0 dev 离线视频无网络时，无法播放，demo里复现

### ISSUE THREAD

**Issue by sunlei4076** [easefun/polyv-ios-client-demo#40]

**Comment by sunlei4076** [comment]
演示视频

[IMG_1153.mov.zip](https://github.com/easefun/polyv-ios-client-demo/files/1169302/IMG_1153.mov.zip)

**Comment by bqlin** [comment]
我也发现是有这个问题。你用的是iOS 10.3 吗？我这边播放离线视频，抓包并没有发现有数据请求，因此可能是 info.plist 或其他配置的影响。目前正在寻找解决方案。

**Comment by sunlei4076** [comment]
是iOS10.3
无网络时没有进行网络请求的
AlicloudReachabilityManager导致的？
在无网络时不请求？

**Comment by bqlin** [comment]
还真是这样，感谢你的建议。这几天修完下载器的一些问题后就会发布新版本。
