### ISSUE TITLE
SDK的vid判断机制有问题吧   使用同一个Vid  有时能播放 有时不能播放

### ISSUE THREAD

**Issue by ConnyYue** [easefun/polyv-ios-client-demo#43]
有时候会崩溃  然后我在setvid加了一个trycatch 打了一个全局断电  会崩溃在PLVMoviePlayerController vidAvailable      但是多播放几次  忽然又能成功播放了  这是什么原因呢  应该不是App的问题吧

**Comment by bqlin** [comment]
这是获取不到 userid 导致的，至于为何获取不到 userid，可能用户信息这部分没配置好。
