### ISSUE TITLE
今日更新SDK遇到一个编译错误

### ISSUE THREAD

**Issue by ConnyYue** [easefun/polyv-ios-client-demo#45]
duplicate symbol _OBJC_IVAR_$__FBKVOInfo._state in:
    /Users/yuechen/Library/Developer/Xcode/DerivedData/ehanceCourse-gvalitdcojdgbfclebheyzfmsrbc/Build/Products/Debug-iphonesimulator/KVOController/libKVOController.a(FBKVOController.o)
    /Users/yuechen/Home/CodeHome/enhanceCourse/EHCourse/Lib/libpolyvSDK/libpolyvSDK.a(PLV_FBKVOController.o)
ld: 14 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by bqlin** [comment]
最新的版本已修复该问题。
